export const WEB_MAX_CONTENT_WIDTH = 600;
export const WEB_MAX_WIDE_CONTENT_WIDTH = 1200;
export const LISTA_RESERVAS_ATIVIDADE_MAX_WIDTH = 800;
export const PROGRAMACAO_ATIVIDADES_REPORT_WIDTH = 1100;
export const PROGRAMACAO_ATIVIDADES_ATIVIDADE_COL_WIDTH = 280;
export const RELATORIO_LISTA_ESPERA_REPORT_WIDTH = 1100;
export const RELATORIO_LISTA_ESPERA_NOME_COL_WIDTH = 220;
export const RELATORIO_LISTA_ESPERA_ATIVIDADE_COL_WIDTH = 280;
export const RELATORIO_LISTA_ESPERA_DATA_COL_WIDTH = 130;
export const RELATORIO_LISTA_ESPERA_AVISO_COL_WIDTH = 80;
export const LISTA_USUARIOS_SUSPENSOS_REPORT_WIDTH = 1252;
export const LISTA_USUARIOS_SUSPENSOS_NOME_COL_WIDTH = 220;
export const LISTA_USUARIOS_SUSPENSOS_TELEFONE_COL_WIDTH = 150;
export const LISTA_USUARIOS_SUSPENSOS_ATIVIDADE_COL_WIDTH = 220;
export const LISTA_USUARIOS_SUSPENSOS_DATA_COL_WIDTH = 130;
export const LISTA_USUARIOS_SUSPENSOS_STATUS_COL_WIDTH = 90;
export const LISTA_USUARIOS_SUSPENSOS_ACTIONS_COL_WIDTH = 72;
export const MAPA_FREQUENCIA_NAME_COL_WIDTH = 300;
export const MAPA_FREQUENCIA_STATUS_COL_WIDTH = 70;
export const MAPA_FREQUENCIA_COL_LATERAL_SPACING = 4;
export const MAPA_FREQUENCIA_ROW_END_PADDING = 16;
export const MAPA_FREQUENCIA_REPORT_WIDTH =
  MAPA_FREQUENCIA_NAME_COL_WIDTH +
  MAPA_FREQUENCIA_STATUS_COL_WIDTH * 10 +
  MAPA_FREQUENCIA_ROW_END_PADDING;
export const LOGADOS_SCREEN_MAX_WIDTH = 1680;
export const LOGADOS_TABLE_MIN_WIDTH = 1620;
export const HOME_MAX_BUTTON_WIDTH = 400;
export const ADMINISTRACAO_GESTAO_MAX_WIDTH = 880;
export const CLUB_SELECTION_MODAL_MAX_WIDTH = 400;
export const CLUB_SELECTION_MODAL_LARGE_SCREEN_BREAKPOINT = 600;
